repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: rust-fix
        name: Rust Fix
        pass_filenames: false
        language: system
        entry: make fix
      - id: rust-fmt
        name: Rust Format
        pass_filenames: false
        language: system
        entry: make fmt
      - id: rust-lint
        name: Rust Lint
        pass_filenames: false
        language: system
        entry: make lint
      - id: rust-docs
        name: Rust Doc Generation Check
        pass_filenames: false
        language: system
        entry: make docs
