[package]
name = "dean"
version = "0.1.0"
edition = "2021"
authors = ["fede@federico.barcelona"]
description = "Static Dependency Analyzer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"

[dev-dependencies]
mockall = "0.11.0"
rspec = "1.0.0"
expects = { git = "https://github.com/tembleking/expects", branch = "master" }
