[package]
name = "dean"
version = "0.1.0"
edition = "2021"
authors = ["fede@federico.barcelona"]
description = "Static (De)pendency (An)alyzer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
clap = { version = "3.1.3", features = ["derive"] }
ureq = { version = "2.4.0", features = ["json"] }
regex = "1.5.4"

[dev-dependencies]
mockall = "0.11.0"
expects = { git = "https://github.com/tembleking/expects", branch = "master" }
